### PR TITLE
Add new post: How to work with Planes in three.js

### PR DESCRIPTION
**Pull request by nikolas**

### CODE REVIEW

**Comment by nikolas** [comment]
I like the image you made as the social media image, Zarina. By the way, a bunch of these images are from the Normal (geometry) wikipedia page: https://en.wikipedia.org/wiki/Normal_(geometry) These are all in the public domain and I don't think we need to do anything special to use them.

**Comment by nikolas** [comment]
Oh woops - actually, this one is under the Creative Commons Attribution license. We should probably add a "source" note: https://en.wikipedia.org/wiki/File:Surface_normals.svg

**Comment by zmustapha** [comment]
Yeah sure. Please add the source attribution in your post, in the caption.

**Comment by nikolas** [comment]
Done. I linked all three: https://github.com/ccnmtl/compiled/pull/193

**Pull request merged**
